name = "syllanavi"
compatibility_date = "2024-12-05"
assets = { directory = "./build/client" }
compatibility_flags = ["nodejs_compat"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "database"
database_id = "00000000-0000-0000-0000-000000000000"